name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          #cache: 'npm'

      - name: "Install Backend Dependencies"
        working-directory: ./backend
        run: npm install

      - name: "Install Frontend Dependencies"
        working-directory: ./frontend
        run: npm install

      - name: "Build Frontend"
        working-directory: ./frontend
        run: npm run build

      - name: "Skipping tests (no test setup yet)"
        run: echo "No tests configured yet — skipping"
